name: Deploy Vite App to GitHub Pages under /bd-25

on:
  push:
    branches:
      - main # adjust if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Needed to push to gh-pages branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build Vite app
        run: npm run build

      - name: Move build output into /bd-25 subfolder
        run: |
          mkdir tmp
          mv dist tmp/bd-25
          mv tmp dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
